import "./globals.css";
import type { Metadata } from "next";
import Background from "@/components/Background";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-dvh text-neutral-900">
        <Background />
        <div className="min-h-dvh flex items-start md:items-center justify-center p-4 md:p-8">
          <div>
            {/* <div className="w-full max-w-5xl rounded-xl bg-[#1e140]/80 backdrop-blur-sm"> */}
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
